BUnarchiver
ownership_policy
Ownership of unarchived objects will be transferred to the caller.
Haiku R1
friend class BArchivable
uint32 BUnarchiver::_reserved[2][2]
const BMessage* BUnarchiver::fArchive
bool BUnarchiver::fFinished
BUnarchiveManager* BUnarchiver::fManager
BUnarchiver::BUnarchiver(const BMessage *archive)
Constructs a BUnarchiver object to manage archive.
To guarantee that your AllUnarchived() method will be called during archival, you must create a BUnarchiver object in your archive constructor. It is necessary to do this even if you won't use the BUnarchiver object in your archive constructor. Do not construct a BUnarchiver object without first calling BUnarchiver::PrepareArchive() on archive. It is only safe to build a BUnarchiver without this call in your AllUnarchived() implementation. BUnarchiver::PrepareArchive() Haiku R1
BUnarchiver::~BUnarchiver()
Destroys a BUnarchiver object.
Calls this objects Finish() method, if it has not yet been called. Haiku R1
const BMessage * BUnarchiver::ArchiveMessage() const
Returns the BMessage* used to construct this BUnarchiver.
This is the archive that FindObject() uses.
void BUnarchiver::AssumeOwnership(BArchivable *archivable)
Become the owner of archivable.
After calling this method you are responsible for deleting the archivable. archivable The archivable object. Haiku R1
status_t BUnarchiver::EnsureUnarchived(const char *name, int32 index=0)
Ensure the object archived under name at index is unarchived and instantiated.
name The archive name. index The archive index. A status code. Haiku R1
References B_DONT_ASSUME_OWNERSHIP, FindObject.
status_t BUnarchiver::EnsureUnarchived(int32 token)
Ensure the object represented by token is unarchived and instantiated.
token the object token A status code. Haiku R1
References B_DONT_ASSUME_OWNERSHIP, GetObject.
status_t BUnarchiver::FindObject(const char *name, int32 index, ownership_policy owning, BArchivable *&archivable)
status_t BUnarchiver::FindObject(const char *name, int32 index, ownership_policy owning, T *&object)
Recover an object that had previously been archived using the BArchiver::AddArchivable() method.
If the object has not yet been instantiated, and this request is not coming from an AllUnarchived() implementation, the object will be instantiated now. If the retrieved object is not of the type T, then this method will fail. If this method fails, you will not receive ownership of the object, no matter what you specified in owning. T The type of object you wish to find. name The name that was passed to BArchiver::AddArchivable() when adding this object. index The index of the object you wish to recover (0-based, like BMessage::FindData(). owning Dictates whether or not you wish to take ownership of the retrieved object. object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References B_ASSUME_OWNERSHIP, FindObject, NULL, RelinquishOwnership.
status_t BUnarchiver::FindObject(const char *name, int32 index, T *&object)
Recover and take ownership of an object that had previously been archived using the BArchiver::AddArchivable() method.
T The type of object you wish to find. name The name that was passed to BArchiver::AddArchivable() when adding this object. index The index of the object you wish to recover (0-based, like BMessage::FindData(). object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References B_ASSUME_OWNERSHIP, FindObject.
status_t BUnarchiver::FindObject(const char *name, ownership_policy owning, T *&object)
Recover an object at index 0 that had previously been archived using the BArchiver::AddArchivable() method.
Equivalent to calling FindObject(name, 0, owning, object). T The type of object you wish to find. name The name that was passed to BArchiver::AddArchivable() when adding this object. owning Dictates whether or not you wish to take ownership of the retrieved object. object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References FindObject.
status_t BUnarchiver::FindObject(const char *name, T *&object)
Recover and take ownership of an object at index 0 that had previously been archived using the BArchiver::AddArchivable() method.
Equivalent to calling FindObject(name, 0, BUnarchiver::B_ASSUME_OWNERSHIP, object). T The type of object you wish to find. name The name that was passed to BArchiver::AddArchivable() when adding this object. object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References B_ASSUME_OWNERSHIP.
Referenced by EnsureUnarchived, FindObject.
status_t BUnarchiver::Finish(status_t err=B_OK)
Report any unarchiving errors and possibly complete the archiving session.
This method may finish an unarchiving session (triggering the call of all instantiated objects' AllUnarchived() methods) if the following conditions are true: No errors have been reported to this or any other BUnarchiver object within this session. This is the last remaining BUnarchiver that has not had its Finish() method invoked. If you call this method with an error code not equal to B_OK, then this unarchiving session has failed, instantiated objects will not have their AllUnarchived() methods called, and any subsequent calls to this method on any BUnarchiver objects in this session will return your error code. Furthermore, any objects that have been instantiated, but have not had their ownership assumed by another object will now be deleted (excluding the root object). The first error reported in this unarchiving session, or B_OK. Haiku R1
status_t BUnarchiver::GetObject(int32 token, ownership_policy owning, BArchivable *&object)
status_t BUnarchiver::GetObject(int32 token, ownership_policy owning, T *&object)
Recover an object by token that was archived by a BArchiver object. If the object has not yet been instantiated, and this request is not coming from an AllUnarchived() implementation, the object will be instantiated now.
If the retrieved object is not of the type T, then this method will fail. If this method fails, you will not receive ownership of the object, no matter what you specified in owning. T The type of object you wish to find. token The token you got for this object from BArchiver::GetTokenForArchivable() during archival. owning Whether or not you wish to take ownership of the retrieved object. object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References B_ASSUME_OWNERSHIP, GetObject, NULL, RelinquishOwnership.
status_t BUnarchiver::GetObject(int32 token, T *&object)
Recover and take ownership of an object represented by token.
Equivalent to calling GetObject(token, B_ASSUME_OWNERSHIP, object) T The type of object you wish to find. token The token you got for this object from BArchiver::GetTokenForArchivable() during archival. object The return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References B_ASSUME_OWNERSHIP.
Referenced by EnsureUnarchived, GetObject.
bool BUnarchiver::IsInstantiated(const char *name, int32 index=0)
Checks whether the object archived under name at index has been instantiated in this session.
name The archive name. index The arcive token. true if instantiated, false otherwise. Haiku R1
bool BUnarchiver::IsInstantiated(int32 token)
Checks whether the object represented by token has been instantiated in this session.
token The object token. true if instantiated, false otherwise Haiku R1
void BUnarchiver::RelinquishOwnership(BArchivable *archivable)
Relinquish ownership of archivable. If archivable remains unclaimed at the end of the unarchiving session, it will be deleted (unless it is the root object).
archivable The archivable object. Haiku R1
Referenced by FindObject, GetObject.
status_t BUnarchiver::InstantiateObject(BMessage *archive, T *&object)
Attempt to instantiate an object of type T from BMessage* from.
If the instantiated object is not of type T, then it will be deleted, and this method will return B_BAD_TYPE. This method is similar to the instantiate_object() function, but provides error reporting and protection from memory leaks. from The BMessage to instantiate from. object Return parameter for the retrieved object of type T. A status code. B_OK The object retrieved was of type T. B_BAD_TYPE The object retrieved was not of type T. Haiku R1
References InstantiateObject, NULL.
Referenced by InstantiateObject.
status_t BUnarchiver::InstantiateObject(BMessage *from, BArchivable *&object)
static bool BUnarchiver::IsArchiveManaged(const BMessage *archive)
Checks whether archive was managed by a BArchiver object.
This method can be used to maintain archive backwards-compatibility for a class that has been updated to use the BArchiver class. If there is a possibility that you are may dealing with a legacy archive, you can use this method to find out before calling any methods on your BUnarchiver object. Here is an example of how you might use this method. Note that you must still call PrepareArchive(archive) either way. MyArchivableClas::MyArchivableClass(BMessage*archive) : BArchivable(BUnarchiver::PrepareArchive(archive)) { BUnarchiverunarchiver(archive); if(BUnarchiver::IsArchiveManaged(archive)){ //...callstoFindObject()orGetObject()here... }else{ //...callstoBMessage::FindMessage()here... } } Whether archive was managed by a BArchiver object. true if archive was managed by a BArchiver object. false otherwise. Haiku R1
static BMessage * BUnarchiver::PrepareArchive(BMessage *&archive)
Prepares archive for use by a BUnarchiver.
This method must be called if you plan to use a BUnarchiver on an archive. It must be called once for each class an object inherits from that will use a BUnarchiver. This method must be called before a call to the archive constructor of your parent class. Notice the use of this method in the example provided below. MyArchivableClas::MyArchivableClas(BMessage*archive) : BArchivable(BUnarchiver::PrepareArchive(archive)) { //... } archive The archive you wish to have prepared. The same BMessage as is passed in. Haiku R1
BUnarchiver::BUnarchiver()
BUnarchiver::BUnarchiver(const BUnarchiver &)
void BUnarchiver::_CallDebuggerIfManagerNull()
void BUnarchiver::RegisterArchivable(BArchivable *archivable)