BReference
Type* BReference< Type >::fObject
BReference< Type >::BReference()
Creates a reference without initializing it.
An uninitialized references behaves similarly to a NULL pointer.
BReference< Type >::BReference(const BReference< OtherType > &other)
BReference< Type >::BReference(const BReference< Type > &other)
Copy constructor.
The reference is set to the same object as the source. The reference count of the target object is incremented.
References BReference< Type >::Get, BReference< Type >::SetTo.
BReference< Type >::BReference(Type *object, bool alreadyHasReference=false)
Creates and initialize a reference.
The reference is set to the pointed object. If the parameter is set to true, the reference count is not incremented, this should only be used when referencing a freshly constructed object.
References BReference< Type >::SetTo.
BReference< Type >::~BReference()
Destructor.
The reference count of the target object is decremented.
References BReference< Type >::Unset.
ConstType * BReference< Type >::Detach()
Detach the pointed object from the reference.
a raw pointer to the target object. This returns the pointed object and unsets the reference, without decrementing the object reference count. It is used to transfer ownership of the reference to something else.
References NULL.
ConstType * BReference< Type >::Get() const
Get the target object.
a raw pointer to the target object.
Referenced by BReference< Type >::BReference.
bool BReference< Type >::IsSet() const
BReference< Type >::operator Type *() const
bool BReference< Type >::operator!=(const BReference< Type > &other) const
bool BReference< Type >::operator!=(const Type *other) const
Type & BReference< Type >::operator*() const
Type * BReference< Type >::operator->() const
BReference & BReference< Type >::operator=(const BReference< OtherType > &other)
BReference & BReference< Type >::operator=(const BReference< Type > &other)
BReference & BReference< Type >::operator=(Type *other)
bool BReference< Type >::operator==(const BReference< Type > &other) const
bool BReference< Type >::operator==(const Type *other) const
void BReference< Type >::SetTo(Type *object, bool alreadyHasReference=false)
Sets a new target for the reference.
The reference to the previously targetted object is released. A reference to the new object is acquired only if alreadyHasReference is false.
References NULL, BReference< Type >::Unset.
Referenced by BReference< Type >::BReference.
void BReference< Type >::Unset()
Unsets the reference.
The targetted object is released. The reference is unset and can't be used to access it anymore.
References NULL.
Referenced by BReference< Type >::~BReference, BReference< Type >::SetTo.