BLayout
BView * BLayout::Owner() const
Returns the Owner of this layout, i.e. the view this layout manages.
Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::Cards, BLayoutBuilder::Grid< ParentBuilder >::Grid, BLayoutBuilder::Group< ParentBuilder >::Group.
BView * BLayout::TargetView() const
Returns the target view of this layout.
The target view of a layout becomes the parent of any BView's in this layout, as well as the BView's returned by BLayoutItem::View() for each BLayoutItem in this layout. Haiku R1
BView * BLayout::View()
Returns the same BView* as BLayout::Owner(), this method is inherited from BLayoutItem.
Haiku R1
BLayoutItem * BLayout::AddView(BView *child)
Creates a BLayoutItem to represent a BView, and adds that item to this layout.
child is added to this BLayout's target view. The BLayoutItem created to represent child, or NULL if there was an error. child The BView to be added to this BLayout. Haiku R1
BLayoutItem * BLayout::AddView(int32 index, BView *child)
Creates a BLayoutItem to represent child, and adds that item at index to this layout. child is added to this BLayout's target view.
Haiku R1
bool BLayout::AddItem(BLayoutItem *item)
Adds a BLayoutItem to this layout, and adds the BView it represents to this BLayout's target view.
item The BLayoutItem to be added. true if the item was added, false otherwise. Haiku R1
bool BLayout::AddItem(int32 index, BLayoutItem *item)
Adds item to this layout, and adds the BView item represents to this BLayout's target view.
item The BLayoutItem to be added. index The index at which to add item. If index is out of bounds, item will be added at the end. If index is somewhere between the first and last indices, then items from index to the end will be shuffled over by one. true if the item was added, false otherwise. Haiku R1
bool BLayout::RemoveView(BView *child)
Removes and deletes all BLayoutItem representing a BView from this layout.
child The BView to be removed. true if the item was removed, false otherwise. Haiku R1
bool BLayout::RemoveItem(BLayoutItem *item)
Removes a BLayoutItem from this layout, and also removes the view it represents from this BLayout's target view.
item The BLayoutItem to be removed item is not deleted, you must delete it manually, or add it to another BLayout. item->View(), even when it is removed from the target view, is not deleted. If you want it deleted, you must delete it yourself! true if the item was removed, false otherwise. Haiku R1
BLayoutItem * BLayout::RemoveItem(int32 index)
Remove the BLayoutItem at index.
RemoveItem(BLayoutItem*) The BLayoutItem that was removed. Haiku R1
BLayoutItem * BLayout::ItemAt(int32 index) const
Get the BLayoutItem at index. Returns NULL if index is out of bounds.
Haiku R1
int32 BLayout::CountItems() const
Get the number of BLayoutItem s in this layout.
Haiku R1
int32 BLayout::IndexOfItem(const BLayoutItem *item) const
Get the index of a BLayoutItem in this layout.
item The BLayoutItem whose index you want. -1 item was not found in this BLayout. Haiku R1
int32 BLayout::IndexOfView(BView *child) const
Get the index of child in this layout.
This finds the index of views added through BLayout::AddView(), not the index of an item which represents child that was added through BLayout::AddItem(). Haiku R1
bool BLayout::AncestorsVisible() const
Get the visibility of the ancestors of this layout.
If a BLayout is connected to a BView, this will always return true. If a BLayout is nested in another layout (it was passed to AddItem()), then this will reflect the visibility of this BLayout's parent layout. If any layout is hidden (by BLayout::SetVisible()) between this layout and its target BView's layout, then this method will return false. Haiku R1
BRect BLayout::LayoutArea()
Returns the on-screen area this layout has received to lay out its items in.
The return value is in the coordinate space of this BLayout's target view. If this BLayout is attached directly to a BView, then LayoutArea().LeftTop() == B_ORIGIN . Haiku R1
void BLayout::VisibilityChanged(bool show)
Method to be called by derived classes in their SetVisible() implementation. Calls AncestorVisibilityChanged() on the items in this BLayout.
show true to show, false to hide. Haiku R1
void BLayout::InvalidateLayout(bool children=false)
Invalidate this layout and any cached data this layout has relating to positioning and sizing of its items.
Invalidating a BLayout also invalidates the view it is connected to (if there is one) and the BLayout this layout (or this BLayout's view) resides in. Although this method is virtual, you should not override it, override the BLayout::LayoutInvalidated() hook instead. This method should be called whenever the layout becomes invalid. This might happen if the size constraints of an item in this layout change, this layout is given more or less space than it previously had, or an object in this layout has had its InvalidateLayout() method called. BView::InvalidateLayout(), BLayoutItem::InvalidateLayout(), BLayout::LayoutInvalidated() Haiku R1
void BLayout::RequireLayout()
Flag this layout as stale, i.e. any cached data may still be valid, but the items need to be repositioned or resized.
Haiku R1
bool BLayout::IsValid()
Returns whether this layout has been invalidated (via BLayout::InvalidateLayout()) and has not yet been validated (by doing a layout, or by its ResetLayoutInvalidation() method.
Haiku R1
void BLayout::EnableLayoutInvalidation()
Re-enable layout invalidation after a call to DisableLayoutInvalidation().
Haiku R1
void BLayout::DisableLayoutInvalidation()
Disable layout invalidation notifications, i.e. calls to this object's InvalidateLayout() method.
Haiku R1
void BLayout::ResetLayoutInvalidation()
Reset layout invalidation, causing InvalidateLayout calls to proceed again. This method should be called once any cached data has been validated, or updated to valid values.
Haiku R1
void BLayout::Relayout(bool immediate=false)
Request this BLayout to reposition and resize its items as required.
If immediate is false, and there is already a request to have the window this layout resides in re-laid-out, then the layout will happen at that time. If immediate is true, and there is no such pending request, nor is this BLayout's parent layout in the process of laying out its items, then this BLayout will now layout its items. immediate Whether or not to Relayout immediately or wait for pending requests first. Haiku R1
void BLayout::LayoutItems(bool force=false)
If there is no layout currently ongoing, and force is false, creates a new BLayoutContext and calls the DoLayout() method of this BLayout and any BLayout's nested in this BLayout.
This method also guarantees that the owner view of this layout (as returned by BLayout::Owner()) performs a layout as well (if it is suitable to do so). force Force the LayoutItems. Haiku R1
BLayoutContext * BLayout::LayoutContext() const
Returns the BLayoutContext this BLayout is currently operating in, or NULL.
Haiku R1
status_t BLayout::Archive(BMessage *into, bool deep=true) const
Archives this layout into archive. If deep is true, also archives the items in this layout, calling ItemArchived() for each one.
Haiku R1
status_t BLayout::AllUnarchived(const BMessage *from)
Unarchives the BLayoutItem's for this layout, calling ItemUnarchived() for each one.
Haiku R1
status_t BLayout::ItemArchived(BMessage *into, BLayoutItem *item, int32 index) const
Hook for derived classes to add data specific to item to the into BMessage. item resides at index.
The same archive is passed to BLayout::ItemArchived() for all items, so any data added for each item will be stored in an array. Haiku R1
status_t BLayout::ItemUnarchived(const BMessage *from, BLayoutItem *item, int32 index)
Hook for derived classes to retrieve data specific to item from the from BMessage. item resides at index.
The same archive is passed to BLayout::ItemArchived() for all items, so any data added for each item will be stored in an array. You should pass index to the BMessage methods you will be using in this method. Haiku R1
bool BLayout::ItemAdded(BLayoutItem *item, int32 atIndex)
Hook method called when item is added to this layout.
item The BLayoutItem that is being added. atIndex The index of the BLayoutItem. true on succcess, false if item will not be added. This is a good time to allocate data for a BLayoutItem and attach it to item via BLayoutItem::SetLayoutData(). Haiku R1
void BLayout::ItemRemoved(BLayoutItem *item, int32 fromIndex)
Hook method called when item is removed from this layout.
item The BLayoutItem being removed. fromIndex The index where item used to reside. When this hook is called, item is not yet completely removed. It can no longer be accessed with LayoutItemAt(), nor does it contribute to the value of CountItems(), but the item has not yet had its ItemDetached() hook called. This is a good time to delete the data you've attached to item via BLayoutItem::SetLayoutData(). Haiku R1
void BLayout::LayoutInvalidated(bool children)
Hook method called when this layout becomes invalid. This is a good place to clear any caches your object might hold. children Whether or not child layouts have also been invalidated. Haiku R1
void BLayout::DoLayout()=0
Implemented by derived classes to position and resize the items in this layout.
Haiku R1
void BLayout::OwnerChanged(BView *was)
Hook method called when this layout is attached to a BView.
was The previous owner of this BLayout, for new BLayout s, this will be NULL. Haiku R1
void BLayout::AttachedToLayout()
Hook method inherited from BLayoutItem, classes derived from BLayout must include the BLayout version of this method in their implementation.
Haiku R1
void BLayout::DetachedFromLayout(BLayout *layout)
Hook method inherited from BLayoutItem, classes derived from BLayout must include the BLayout version of this method in their implementation.
layout The BLayout that this BLayout was detached from. Haiku R1
void BLayout::AncestorVisibilityChanged(bool shown)
Hook method inherited from BLayoutItem, classes derived from BLayout must include the BLayout version of this method in their implementation.
Haiku R1
friend class BView
uint32 BLayout::_reserved[10][10]
bool BLayout::fAncestorsVisible
BLayoutContext* BLayout::fContext
int32 BLayout::fInvalidationDisabled
BList BLayout::fItems
BList BLayout::fNestedLayouts
BView* BLayout::fOwner
uint32 BLayout::fState
BView* BLayout::fTarget
BLayout::BLayout()
Default constructor.
After this constructor has finished, this BLayout holds no BLayoutItem's and does not have a target BView. Because a new BLayout does not have a target BView, calls to the AddItem() and AddView() methods will fail. Haiku R1
BLayout::BLayout(BMessage *archive)
Archive constructor.
archive The archive message. Haiku R1
BLayout::~BLayout()
Destructor, deletes all BLayoutItem's that this layout manages, and detaches from this BLayout's owner view if there is one.
Destructor method. Each BLayoutItem's BView (as returned by BLayoutItem::View()) is also removed from their parent. Because nested BLayout's are treated as BLayoutItem's, any layouts nested in this BLayout will be deleted. Haiku R1 Standard Destructor. Haiku R1
virtual status_t BLayout::Perform(perform_code d, void *arg)
Perform some action (Internal method defined for binary compatibility purposes).
virtual status_t BLayout::AllArchived(BMessage *archive) const
Method relating to the use of BArchiver.
This hook function is called once the first BArchiver that was created in an archiving session is either destroyed, or has its Finish() method called. Implementations of this method can be used, in conjunction with BArchiver::IsArchived(), to reference objects in your archive that you do not own, depending on whether or not those objects were archived by their owners. Implementations of this method should call the implementation of their parent class, the same as for the Archive() method. To guarantee that your AllArchived() method will be called during archival, you must create a BArchiver object in your Archive() implementation. You should archive any objects you own in your Archive() method implementation, and NOT your AllArchived() method. BArchiver BArchiver::Finish() Haiku R1
BLayout::BLayout(const BLayout &)
void BLayout::_LayoutWithinContext(bool force, BLayoutContext *context)
virtual void BLayout::_ReservedLayout1()
virtual void BLayout::_ReservedLayout10()
virtual void BLayout::_ReservedLayout2()
virtual void BLayout::_ReservedLayout3()
virtual void BLayout::_ReservedLayout4()
virtual void BLayout::_ReservedLayout5()
virtual void BLayout::_ReservedLayout6()
virtual void BLayout::_ReservedLayout7()
virtual void BLayout::_ReservedLayout8()
virtual void BLayout::_ReservedLayout9()
void BLayout::operator=(const BLayout &)
void BLayout::SetOwner(BView *owner)
void BLayout::SetTarget(BView *target)