BSpaceLayoutItem
uint32 BSpaceLayoutItem::_reserved[2][2]
BAlignment BSpaceLayoutItem::fAlignment
BRect BSpaceLayoutItem::fFrame
BSize BSpaceLayoutItem::fMaxSize
BSize BSpaceLayoutItem::fMinSize
BSize BSpaceLayoutItem::fPreferredSize
bool BSpaceLayoutItem::fVisible
BSpaceLayoutItem::BSpaceLayoutItem(BMessage *archive)
Constructs a BSpaceLayoutItem from an archive message.
This method is usually not called directly, if you want to build a space layout item from an archived message you should call Instantiate() instead because it can handle errors properly. archive The BMessage that contains the space layout item. Haiku R1
BSpaceLayoutItem::BSpaceLayoutItem(BSize minSize, BSize maxSize, BSize preferredSize, BAlignment alignment)
Create a space layout item with specific properties.
See the CreateGlue(), CreateVerticalStrut() and CreateHorizontalStruct static methods to create common space items. minSize The minimum size for this item. maxSize The maximum size for this item. preferredSize The preferred size for this item. alignment The alignment of this item. Haiku R1
BSpaceLayoutItem::~BSpaceLayoutItem()
Destructor.
Haiku R1
BAlignment BSpaceLayoutItem::Alignment()
Returns the requested alignment for this item. The value returned from this method is used in BLayoutItem::AlignInFrame(), which BLayouts use to position and resize items. In a vertical BGroupLayout, for example, although each item recieves the same horizontal area, each item can use that area differently, aligning to the left, right or center for example. Haiku R1
virtual status_t BSpaceLayoutItem::Archive(BMessage *into, bool deep=true) const
Archive the object into a BMessage.
You should call this method from your derived implementation as it adds the data needed to instantiate your object to the message. into The message you store your object in. deep If true, all children of this object should be archived as well. B_OK The archive operation was successful. B_BAD_VALUE NULL archive message. B_ERROR The archive operation failed. BeOS R3
BRect BSpaceLayoutItem::Frame()
Return the bounding frame of this item. The returned BRect is in the coordinate system of the target view of the BLayout this item belongs to. Haiku R1
bool BSpaceLayoutItem::IsVisible()
Return the current local visibility of this item.
The visibility is set explicitly through SetVisible(). By default, the layout item is visible. Haiku R1
BSize BSpaceLayoutItem::MaxSize()
Returns the maximum desirable size for this item. Haiku R1
BSize BSpaceLayoutItem::MinSize()
Returns the minimum desirable size for this item. Haiku R1
BSize BSpaceLayoutItem::PreferredSize()
Returns the preferred size for this item. Haiku R1
void BSpaceLayoutItem::SetExplicitAlignment(BAlignment alignment)
Set this item's explicit alignment, to be used in Alignment(). Haiku R1
void BSpaceLayoutItem::SetExplicitMaxSize(BSize size)
Set this item's explicit max size, to be used in MaxSize(). Haiku R1
void BSpaceLayoutItem::SetExplicitMinSize(BSize size)
Set this item's explicit min size, to be used in MinSize(). This forces the minimal size for the item and overrides any constraints that would normally be used to compute it. Most importantly, the minimal size of children is ignored, so setting this can lead to the children not fitting the view. Haiku R1
void BSpaceLayoutItem::SetExplicitPreferredSize(BSize size)
Set this item's explicit preferred size, to be used in PreferredSize(). Haiku R1
void BSpaceLayoutItem::SetFrame(BRect frame)
Set the bounding frame of this item. frame is in the coordinate system of the target view of the BLayout that this item belongs to. Haiku R1
void BSpaceLayoutItem::SetVisible(bool visible)
Set the visibility of this space layout item.
visible The desired visibility of the layout item. Haiku R1
static BSpaceLayoutItem * BSpaceLayoutItem::CreateGlue()
Create a layout item that acts like glue.
This type of space layout item has no minimum size, and expands to the maximum available space in all directions. Creates a new BSpaceLayoutItem and returns ownership to the caller. Haiku R1
Referenced by BLayoutBuilder::Group< ParentBuilder >::AddGlue, BLayoutBuilder::Grid< ParentBuilder >::AddGlue.
static BSpaceLayoutItem * BSpaceLayoutItem::CreateHorizontalStrut(float width)
Create a layout item that horizontally expands to a maximum width.
The item has no minimum size, meaning that if the total available width is smaller than the maximum width, the strut will use the available space. width The maximum width. Creates a new BSpaceLayoutItem and returns ownership to the caller. Haiku R1
Referenced by BLayoutBuilder::Group< ParentBuilder >::AddStrut.
static static BSpaceLayoutItem * BSpaceLayoutItem::CreateVerticalStrut(float height)
Create a layout item that vertically expands to a maximum height.
The item has no minimum size, meaning that if the total available height is smaller than the maximum width, the strut will use the available space. height The maximum height. Creates a new BSpaceLayoutItem and returns ownership to the caller. Haiku R1
Referenced by BLayoutBuilder::Group< ParentBuilder >::AddStrut.
static BArchivable * BSpaceLayoutItem::Instantiate(BMessage *from)
Instantiate the item from the message from.
Haiku R1
BSpaceLayoutItem::BSpaceLayoutItem(const BSpaceLayoutItem &)
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem1()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem10()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem2()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem3()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem4()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem5()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem6()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem7()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem8()
virtual void BSpaceLayoutItem::_ReservedSpaceLayoutItem9()
void BSpaceLayoutItem::operator=(const BSpaceLayoutItem &)