BAffineTransform
const double BAffineTransform::kDefaultEpsilon
Undocumented public variable.
Haiku R1
double BAffineTransform::shx
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, Determinant, InverseDeterminant, operator=, PreRotateBy, PreScaleBy, PreTranslateBy, RotateBy, ScaleBy.
double BAffineTransform::shy
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, Determinant, InverseDeterminant, operator=, PreRotateBy, PreScaleBy, PreTranslateBy, RotateBy, ScaleBy.
double BAffineTransform::sx
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, Determinant, InverseDeterminant, operator=, PreRotateBy, PreScaleBy, PreTranslateBy, RotateBy, ScaleBy.
double BAffineTransform::sy
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, Determinant, InverseDeterminant, operator=, PreRotateBy, PreScaleBy, PreTranslateBy, RotateBy, ScaleBy.
double BAffineTransform::tx
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, operator=, PreTranslateBy, RotateBy, ScaleBy, TranslateBy.
double BAffineTransform::ty
Undocumented public variable.
Haiku R1
Referenced by Apply, ApplyInverse, operator=, PreTranslateBy, RotateBy, ScaleBy, TranslateBy.
BAffineTransform::BAffineTransform()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
Referenced by operator*, operator/.
BAffineTransform::BAffineTransform(const BAffineTransform &copyFrom)
Undocumented public method.
copyFrom Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform::BAffineTransform(double sx, double shy, double shx, double sy, double tx, double ty)
Undocumented public method.
sx Undocumented shy Undocumented shx Undocumented sy Undocumented tx Undocumented ty Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform::~BAffineTransform()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
void BAffineTransform::Apply(BPoint *point) const
Undocumented public method.
point Undocumented Haiku R1
void BAffineTransform::Apply(BPoint *points, uint32 count) const
Undocumented public method.
points Undocumented count Undocumented Haiku R1
BPoint BAffineTransform::Apply(const BPoint &point) const
Undocumented public method.
point Undocumented Undocumented <value> Undocumented Haiku R1
void BAffineTransform::Apply(double *x, double *y) const
Undocumented public method.
x Undocumented y Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
void BAffineTransform::ApplyInverse(BPoint *point) const
Undocumented public method.
point Undocumented Haiku R1
void BAffineTransform::ApplyInverse(BPoint *points, uint32 count) const
Undocumented public method.
points Undocumented count Undocumented Haiku R1
BPoint BAffineTransform::ApplyInverse(const BPoint &point) const
Undocumented public method.
point Undocumented Undocumented <value> Undocumented Haiku R1
void BAffineTransform::ApplyInverse(double *x, double *y) const
Undocumented public method.
x Undocumented y Undocumented Haiku R1
References InverseDeterminant, shx, shy, sx, sy, tx, ty.
double BAffineTransform::Determinant() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy.
status_t BAffineTransform::Flatten(void *buffer, ssize_t size) const
Undocumented public method.
buffer Undocumented size Undocumented Undocumented <value> Undocumented Haiku R1
ssize_t BAffineTransform::FlattenedSize() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::FlipX()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::FlipY()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
bool BAffineTransform::GetAffineParameters(double *translationX, double *translationY, double *rotation, double *scaleX, double *scaleY, double *shearX, double *shearY) const
Undocumented public method.
translationX Undocumented translationY Undocumented rotation Undocumented scaleX Undocumented scaleY Undocumented shearX Undocumented shearY Undocumented Undocumented <value> Undocumented Haiku R1
void BAffineTransform::GetScale(double *sx, double *sy) const
Undocumented public method.
sx Undocumented sy Undocumented Haiku R1
void BAffineTransform::GetScaleAbs(double *sx, double *sy) const
Undocumented public method.
sx Undocumented sy Undocumented Haiku R1
void BAffineTransform::GetTranslation(double *tx, double *ty) const
Undocumented public method.
tx Undocumented ty Undocumented Haiku R1
double BAffineTransform::InverseDeterminant() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy.
Referenced by ApplyInverse.
const BAffineTransform & BAffineTransform::Invert()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
Referenced by MultiplyInverse, operator~, PreMultiplyInverse.
bool BAffineTransform::IsDilation(double epsilon=kDefaultEpsilon) const
Undocumented public method.
epsilon Undocumented Undocumented <value> Undocumented Haiku R1
bool BAffineTransform::IsEqual(const BAffineTransform &other, double epsilon=kDefaultEpsilon) const
Undocumented public method.
other Undocumented epsilon Undocumented Undocumented <value> Undocumented Haiku R1
Referenced by operator!=, operator==.
bool BAffineTransform::IsFixedSize() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
bool BAffineTransform::IsIdentity(double epsilon=kDefaultEpsilon) const
Undocumented public method.
epsilon Undocumented Undocumented <value> Undocumented Haiku R1
bool BAffineTransform::IsValid(double epsilon=kDefaultEpsilon) const
Undocumented public method.
epsilon Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::Multiply(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References PreMultiply.
Referenced by MultiplyInverse, operator*=, PreMultiplyInverse.
const BAffineTransform & BAffineTransform::MultiplyInverse(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References Invert, Multiply.
Referenced by operator/=.
bool BAffineTransform::operator!=(const BAffineTransform &other) const
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References IsEqual.
BAffineTransform BAffineTransform::operator*(const BAffineTransform &other) const
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References BAffineTransform.
const BAffineTransform & BAffineTransform::operator*=(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References Multiply.
BAffineTransform BAffineTransform::operator/(const BAffineTransform &other) const
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References BAffineTransform.
const BAffineTransform & BAffineTransform::operator/=(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References MultiplyInverse.
BAffineTransform & BAffineTransform::operator=(const BAffineTransform &copyFrom)
Undocumented public method.
copyFrom Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
bool BAffineTransform::operator==(const BAffineTransform &other) const
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References IsEqual.
BAffineTransform BAffineTransform::operator~() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
References Invert.
const BAffineTransform & BAffineTransform::PreMultiply(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
Referenced by Multiply, ShearBy.
const BAffineTransform & BAffineTransform::PreMultiplyInverse(const BAffineTransform &other)
Undocumented public method.
other Undocumented Undocumented <value> Undocumented Haiku R1
References Invert, Multiply.
const BAffineTransform & BAffineTransform::PreRotateBy(double angleRadians)
Undocumented public method.
angleRadians Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy.
const BAffineTransform & BAffineTransform::PreScaleBy(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy.
const BAffineTransform & BAffineTransform::PreTranslateBy(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
const BAffineTransform & BAffineTransform::Reset()
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::RotateBy(const BPoint &center, double angle)
Undocumented public method.
center Undocumented angle Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::RotateBy(double angle)
Undocumented public method.
angle Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
BAffineTransform BAffineTransform::RotateByCopy(const BPoint &center, double angle) const
Undocumented public method.
center Undocumented angle Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::RotateByCopy(double angle) const
Undocumented public method.
angle Undocumented Undocumented <value> Undocumented Haiku R1
double BAffineTransform::Rotation() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
double BAffineTransform::Scale() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ScaleBy(const BPoint &center, const BPoint &scale)
Undocumented public method.
center Undocumented scale Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ScaleBy(const BPoint &center, double scale)
Undocumented public method.
center Undocumented scale Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ScaleBy(const BPoint &center, double x, double y)
Undocumented public method.
center Undocumented x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ScaleBy(const BPoint &scale)
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ScaleBy(double scale)
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
const BAffineTransform & BAffineTransform::ScaleBy(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
References shx, shy, sx, sy, tx, ty.
BAffineTransform BAffineTransform::ScaleByCopy(const BPoint &center, const BPoint &scale) const
Undocumented public method.
center Undocumented scale Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ScaleByCopy(const BPoint &center, double scale) const
Undocumented public method.
center Undocumented scale Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ScaleByCopy(const BPoint &center, double x, double y) const
Undocumented public method.
center Undocumented x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ScaleByCopy(const BPoint &scale) const
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ScaleByCopy(double scale) const
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ScaleByCopy(double x, double y) const
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::SetScale(double scale)
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::SetScale(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ShearBy(const BPoint &center, const BPoint &shear)
Undocumented public method.
center Undocumented shear Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ShearBy(const BPoint &center, double x, double y)
Undocumented public method.
center Undocumented x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ShearBy(const BPoint &shear)
Undocumented public method.
shear Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::ShearBy(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
References AffineShearing, PreMultiply.
BAffineTransform BAffineTransform::ShearByCopy(const BPoint &center, const BPoint &shear) const
Undocumented public method.
center Undocumented shear Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ShearByCopy(const BPoint &center, double x, double y) const
Undocumented public method.
center Undocumented x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ShearByCopy(const BPoint &shear) const
Undocumented public method.
shear Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::ShearByCopy(double x, double y) const
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::TranslateBy(const BPoint &delta)
Undocumented public method.
delta Undocumented Undocumented <value> Undocumented Haiku R1
const BAffineTransform & BAffineTransform::TranslateBy(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
References tx, ty.
BAffineTransform BAffineTransform::TranslateByCopy(const BPoint &delta) const
Undocumented public method.
delta Undocumented Undocumented <value> Undocumented Haiku R1
BAffineTransform BAffineTransform::TranslateByCopy(double x, double y) const
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
type_code BAffineTransform::TypeCode() const
Undocumented public method.
Undocumented <value> Undocumented Haiku R1
status_t BAffineTransform::Unflatten(type_code code, const void *buffer, ssize_t size)
Undocumented public method.
code Undocumented buffer Undocumented size Undocumented Undocumented <value> Undocumented Haiku R1
static static BAffineTransform BAffineTransform::AffineRotation(double angle)
Undocumented public method.
angle Undocumented Undocumented <value> Undocumented Haiku R1
static static BAffineTransform BAffineTransform::AffineScaling(double scale)
Undocumented public method.
scale Undocumented Undocumented <value> Undocumented Haiku R1
static static BAffineTransform BAffineTransform::AffineScaling(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
static static BAffineTransform BAffineTransform::AffineShearing(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1
Referenced by ShearBy.
static static BAffineTransform BAffineTransform::AffineTranslation(double x, double y)
Undocumented public method.
x Undocumented y Undocumented Undocumented <value> Undocumented Haiku R1