BWindow
void BWindow::AddShortcut(uint32 key, uint32 modifiers, BMessage *message)
Creates a keyboard shortcut that sends a message to the window.
Don't use this method to a create menu shortcut, add a BMenuItem instead. key The character that activates the shortcut, case-insensitive. modifiers A bit mask of modifiers in addition to B_COMMAND_KEY, options include: B_SHIFT_KEY B_OPTION_KEY B_CONTROL_KEY B_MENU_KEY message The message to send when the shortcut is activated. The BWindow takes ownership of the message. BeOS R3
void BWindow::AddShortcut(uint32 key, uint32 modifiers, BMessage *message, BHandler *target)
Creates a keyboard shortcut that sends a message to the specified target.
Don't use this method to a create menu shortcut, add a BMenuItem instead. key The character that activates the shortcut, case-insensitive. modifiers A bit mask of modifiers in addition to B_COMMAND_KEY, options include one or more of the following: B_SHIFT_KEY B_OPTION_KEY B_CONTROL_KEY B_MENU_KEY message The message to send when the shortcut is activated. The BWindow takes ownership of the message. target The handler to send the message to. BeOS R3
bool BWindow::HasShortcut(uint32 key, uint32 modifiers)
Returns whether or not the specified shortcut is set on the window.
key The character to check, case-insensitive. modifiers A bit mask of modifiers in addition to B_COMMAND_KEY, options include one or more of the following: B_SHIFT_KEY B_OPTION_KEY B_CONTROL_KEY B_MENU_KEY true if the window has the specified shortcut, false otherwise. Haiku R1
void BWindow::RemoveShortcut(uint32 key, uint32 modifiers)
Removes the specified shortcut from the window.
The memory used by the shortcut message is freed. key The character to remove, case-insensitive. modifiers A bit mask of modifiers in addition to B_COMMAND_KEY, options include one or more of the following: B_SHIFT_KEY B_OPTION_KEY B_CONTROL_KEY B_MENU_KEY BeOS R3
void BWindow::AddShortcut(uint32 key, uint32 modifiers, BMenuItem *item)
Creates a keyboard shortcut that activates a menu item.
key The character that activates the shortcut, case-insensitive. modifiers A bit mask of modifiers in addition to B_COMMAND_KEY, options include: B_SHIFT_KEY B_OPTION_KEY B_CONTROL_KEY B_MENU_KEY item The menu item to activate. Haiku R1
typedef BLooper BWindow::inherited
status_t _safe_get_server_token_(const BLooper *, int32 *)
void _set_menu_sem_(BWindow *w, sem_id sem)
friend class BAlert
friend class BApplication
friend class BBitmap
friend class BDirectWindow
friend class BFilePanel
friend class BMenuItem
friend class BView
friend class BWindowScreen
friend class BWindowStack
uint32 BWindow::_reserved[9][9]
int32 BWindow::_unused0
uint32 BWindow::_unused1
bool BWindow::_unused4
bool BWindow::_unused5
bool BWindow::_unused6
bool BWindow::fActive
BButton* BWindow::fDefaultButton
window_feel BWindow::fFeel
uint32 BWindow::fFlags
BView* BWindow::fFocus
BRect BWindow::fFrame
bool BWindow::fInTransaction
bool BWindow::fIsFilePanel
BMenuBar* BWindow::fKeyMenuBar
BView* BWindow::fLastMouseMovedView
int32 BWindow::fLastViewToken
::BPrivate::PortLink* BWindow::fLink
window_look BWindow::fLook
float BWindow::fMaxHeight
float BWindow::fMaxWidth
float BWindow::fMaxZoomHeight
float BWindow::fMaxZoomWidth
sem_id BWindow::fMenuSem
float BWindow::fMinHeight
bool BWindow::fMinimized
float BWindow::fMinWidth
bool BWindow::fNoQuitShortcut
bool BWindow::fOffscreen
BRect BWindow::fPreviousFrame
bigtime_t BWindow::fPulseRate
BMessageRunner* BWindow::fPulseRunner
BList BWindow::fShortcuts
short BWindow::fShowLevel
char* BWindow::fTitle
BView* BWindow::fTopView
int32 BWindow::fTopViewToken
bool BWindow::fUpdateRequested
BWindow::BWindow(BMessage *archive)
Archive constructor.
data A pointer to the BMessage object to build the object from. BeOS R3
BWindow::BWindow(BRect frame, const char *title, window_look look, window_feel feel, uint32 flags, uint32 workspace=B_CURRENT_WORKSPACE)
Creates a new BWindow object with the specified look and feel.
frame The inner frame rectangle in the screen coordinate system. title The window title and thread title as "w>title". look The window_look flags, one of the following: B_BORDERED_WINDOW_LOOK No title bar, thin border, no resize control. B_NO_BORDER_WINDOW_LOOK A borderless rectangle with no provisions to move or close the window. B_TITLED_WINDOW_LOOK Like B_DOCUMENT_WINDOW_LOOK, but with a resize corner instead of a resize thumb. B_DOCUMENT_WINDOW_LOOK Large title bar, thick border, draggable resize corner thumb. B_MODAL_WINDOW_LOOK For modal dialogs: no title bar, thick border, resize corner depending on the B_NOT_RESIZABLE flag. B_FLOATING_WINDOW_LOOK For floating sub windows: small title bar, thin border, resize corner. feel The window_feel flags, one of the following: B_NORMAL_WINDOW_FEEL Behaves like a normal, non-modal, non-floating window. B_MODAL_SUBSET_WINDOW_FEEL Blocks all windows in its subset when displayed. Visible only if a window in its subset is visible. B_MODAL_APP_WINDOW_FEEL Blocks all windows in its app when displayed. Visible only if a window in its app is visible. B_MODAL_ALL_WINDOW_FEEL Blocks all windows across the entire system when displayed. Always visible in all workspaces. B_FLOATING_SUBSET_WINDOW_FEEL Floats above all windows in its subset when displayed. Visible only if a window in its subset is the frontmost window. B_FLOATING_APP_WINDOW_FEEL Floats above all windows in its app when displayed. Visible only if a window in its app is the frontmost window. B_FLOATING_ALL_WINDOW_FEEL Floats above all windows across the entire system when displayed. Always visible in all workspaces. flags Mask that defines window attributes: B_NOT_MOVABLE cannot be moved by the user B_NOT_CLOSABLE cannot be closed by the user, no close button displayed B_NOT_ZOOMABLE cannot be zoomed by the user, no zoom button displayed B_NOT_MINIMIZABLE cannot be minimized by the user B_NOT_RESIZABLE cannot be resized by the user B_NOT_H_RESIZABLE cannot be resized horizontally by the user B_NOT_V_RESIZABLE cannot be resized vertically by the user B_AVOID_FRONT cannot be brought to front by the user B_AVOID_FOCUS cannot receive keyboard focus B_WILL_ACCEPT_FIRST_CLICK The first click is processed by the window. B_OUTLINE_RESIZE draws only its outline as it's resized and doesn't draw its contents. B_NO_WORKSPACE_ACTIVATION Causes the current workspace to stay active when activated on another workspace. B_NOT_ANCHORED_ON_ACTIVATE Causes the window to move to the current workspace when activated if it already exists on another workspace. B_QUIT_ON_WINDOW_CLOSE Quit the application when the window closes. B_SAME_POSITION_IN_ALL_WORKSPACES Window maintains its position across workspaces. B_AUTO_UPDATE_SIZE_LIMITS Automatically adjust the size according to layout constraints. B_CLOSE_ON_ESCAPE Close when the user pushes the Escape key. B_NO_SERVER_SIDE_WINDOW_MODIFIERS ?? workspace Mask that indicates which of the 32 potential workspace(s) the window should be displayed in or B_CURRENT_WORKSPACE or B_ALL_WORKSPACES constants. BeOS R3
BWindow::BWindow(BRect frame, const char *title, window_type type, uint32 flags, uint32 workspace=B_CURRENT_WORKSPACE)
Creates a new BWindow object.
frame The inner frame rectangle in the screen coordinate system. title The window title and thread title as "w>title". type window_type flag, one of the following: B_UNTYPED_WINDOW B_TITLED_WINDOW B_MODAL_WINDOW B_DOCUMENT_WINDOW B_BORDERED_WINDOW B_FLOATING_WINDOW flags Mask that defines window attributes: B_NOT_MOVABLE cannot be moved by the user B_NOT_CLOSABLE cannot be closed by the user, no close button displayed B_NOT_ZOOMABLE cannot be zoomed by the user, no zoom button displayed B_NOT_MINIMIZABLE cannot be minimized by the user B_NOT_RESIZABLE cannot be resized by the user B_NOT_H_RESIZABLE cannot be resized horizontally by the user B_NOT_V_RESIZABLE cannot be resized vertically by the user B_AVOID_FRONT cannot be brought to front by the user B_AVOID_FOCUS cannot receive keyboard focus B_WILL_ACCEPT_FIRST_CLICK The first click is processed by the window. B_OUTLINE_RESIZE draws only its outline as it's resized and doesn't draw its contents. B_NO_WORKSPACE_ACTIVATION Causes the current workspace to stay active when activated on another workspace. B_NOT_ANCHORED_ON_ACTIVATE Causes the window to move to the current workspace when activated if it already exists on another workspace. B_QUIT_ON_WINDOW_CLOSE Quit the application when the window closes. B_SAME_POSITION_IN_ALL_WORKSPACES Window maintains its position across workspaces. B_AUTO_UPDATE_SIZE_LIMITS Automatically adjust the size according to layout constraints. B_CLOSE_ON_ESCAPE Close when the user pushes the Escape key. B_NO_SERVER_SIDE_WINDOW_MODIFIERS ?? workspace Mask that indicates which of the 32 potential workspace(s) the window should be displayed in or B_CURRENT_WORKSPACE or B_ALL_WORKSPACES constants. BeOS R3
BWindow::~BWindow()
Destroys the BWindow object and all attached views.
BeOS R3
void BWindow::Activate(bool=true)
Activates or deactivates the window based on active.
The title tab of the active window is drawn more brightly, the window is made frontmost, and it becomes the target of keyboard events. Calling Show() automatically activates the window calling the WindowActivated() hook method. active true to activate the window, false to deactivate the window. BeOS R3
void BWindow::AddChild(BLayoutItem *child)
Add the child layout item to the view hierarchy.
child The child layout item to add. Haiku R1
void BWindow::AddChild(BView *child, BView *before=NULL)
Adds child to the view hierarchy immediately before before.
A view may only have one parent at a time so child must not have already been added to the view hierarchy. If before is NULL then child is added to the end of the view hierarchy. The AttachedToWindow() method is invoked on child and all of its descendent views. child The child view to add. before The sibling view to add child before. BeOS R3
status_t BWindow::AddToSubset(BWindow *window)
Adds window to be in the subset of the BWindow.
A status code. B_OK window was added as a subset of the BWindow. B_BAD_VALUE window is not B_NORMAL_WINDOW_FEEL or the BWindow object's feel is not set to B_MODAL_SUBSET_WINDOW_FEEL or B_FLOATING_SUBSET_WINDOW_FEEL. B_ERROR Could not lock the BWindow object. BeOS R3
status_t BWindow::Archive(BMessage *archive, bool deep=true) const
Archives the object into the data message.
data A pointer to the BMessage object to archive the object into. deep Whether or not to archive child views as well. A status code, B_OK if the object was archived or an error code otherwise. BeOS R3
void BWindow::BeginViewTransaction()
Stall updates to App Server allowing you to batch drawing commands to limit flickering.
Unlike DisableUpdates() the messages are sent but are not processed. Haiku R1
BRect BWindow::Bounds() const
Returns the bounding rectangle of the window.
The bounding rectangle of the window as a BRect in the window's coordinate system. Frame() BeOS R3
void BWindow::CenterIn(const BRect &rect)
Center the window in rect.
rect The rectangle to center the window in. Haiku R1
void BWindow::CenterOnScreen()
Centers the window on the screen the window is currently on.
Haiku R1
void BWindow::CenterOnScreen(screen_id id)
Centers the window on the screen with the passed in id.
Haiku R1
BView * BWindow::ChildAt(int32 index) const
Returns a pointer to the child view found at index.
index The index of the child view to return a pointer of. A pointer to the child view at index or NULL if not found. BeOS R3
void BWindow::Close()
Deprecated alias for BWindow::Quit().
The advised way to close a window is to use BWindow::Quit(). BeOS R3
References Quit.
void BWindow::ConvertFromScreen(BPoint *point) const
Convert point from the screen's coordinate system to the window's coordinate system in place.
point A pointer to a BPoint object to convert. BeOS R3
BPoint BWindow::ConvertFromScreen(BPoint point) const
Returns point converted from the screen's coordinate system to the window's coordinate system.
point A BPoint object to convert. A new BPoint object in the window's coordinate system. BeOS R3
void BWindow::ConvertFromScreen(BRect *rect) const
Convert rect from the screen's coordinate system to the window's coordinate system in place.
rect A pointer to a BRect object to convert. BeOS R3
BRect BWindow::ConvertFromScreen(BRect rect) const
Returns rect converted from the screen's coordinate system to the window's coordinate system.
rect A BRect object to convert. A new BRect object in the window's coordinate system. BeOS R3
void BWindow::ConvertToScreen(BPoint *point) const
Convert point to the screen's coordinate system in place.
point A pointer to a BPoint object to convert. BeOS R3
BPoint BWindow::ConvertToScreen(BPoint point) const
Returns point converted to the screen's coordinate system.
point A BPoint object to convert. A new BPoint object in the screen's coordinate system. BeOS R3
void BWindow::ConvertToScreen(BRect *rect) const
Convert rect to the screen's coordinate system in place.
rect A pointer to a BRect object to convert. BeOS R3
BRect BWindow::ConvertToScreen(BRect rect) const
Returns rect converted to the screen's coordinate system.
rect A BRect object to convert. A new BRect object in the screen's coordinate system. BeOS R3
int32 BWindow::CountChildren() const
Returns the number of child views that the window has.
The number of child views as an int32. BeOS R3
BView * BWindow::CurrentFocus() const
Returns a pointer to the current focus view of the window.
A pointer to the current focus view of the window or NULL if not found. BeOS R3
BRect BWindow::DecoratorFrame() const
Returns the frame rectangle of the window decorator.
The bounding rectangle of the window decorator as a BRect in the screen coordinate system. Haiku R1
BButton * BWindow::DefaultButton() const
Returns a pointer to the default button set on the window.
A pointer to the window's default button or NULL if it doesn't have one. BeOS R3
void BWindow::DisableUpdates()
Suppresses drawing within the window.
If you want the results of several drawing operations to appear in the window all at once you disable updates, draw, and then re-enable updates. BeOS R3
void BWindow::DispatchMessage(BMessage *message, BHandler *handler)
Window's central message-processing method.
This method called automatically as messages arrive in the queue, you should never call DispatchMessage() yourself. Don't override this method in your BWindow subclass. Override MessageReceived() instead to alter the window's message dispatching mechanism. BLooper::DispatchMessage() BeOS R3
void BWindow::EnableUpdates()
Re-enable drawing within the window.
If you want the results of several drawing operations to appear in the window all at once you disable updates, draw, and then re-enable updates. BeOS R3
void BWindow::EndViewTransaction()
Ends a view transaction allowing update to go to App Server again.
Haiku R1
window_feel BWindow::Feel() const
Returns the current window feel flag.
The currently set window feel flag. BeOS R3
BView * BWindow::FindView(BPoint) const
Returns a pointer to the attached view located at the specified point.
point The point to get the view at in the window's coordinate system. A pointer to the BView object or NULL if no view is found. BeOS R3
BView * BWindow::FindView(const char *viewName) const
Returns the attached view with the specified viewName.
viewName The name of the attached view to look for. A pointer to the BView object or NULL if no view is found. BeOS R3
uint32 BWindow::Flags() const
Returns the current window flags.
The currently set window flags. BeOS R3
void BWindow::Flush() const
Flushes the window's connection to App Server causing any pending messages to be processed then returns immediately.
BeOS R3
BRect BWindow::Frame() const
Returns the frame rectangle of the window.
The bounding rectangle of the window as a BRect in the screen coordinate system. Bounds() BeOS R3
void BWindow::FrameMoved(BPoint newPosition)
Hook method that gets called when the window is moved.
newPosition The point of the top left corner of the frame rectangle that the window has been moved to. BeOS R3
void BWindow::FrameResized(float newWidth, float newHeight)
Hook method that gets called when the window is resized.
newWidth The new width of the window. newHeight The new height of the window. BeOS R3
status_t BWindow::GetDecoratorSettings(BMessage *settings) const
Fill out the window's decorator settings into settings.
settings A pointer to a BMessage object to fill out. B_OK if the decorator settings were filled out successfully or an error code otherwise. Haiku R1
BLayout * BWindow::GetLayout() const
Get the layout of the window.
The layout of the window. Haiku R1
void BWindow::GetSizeLimits(float *minWidth, float *maxWidth, float *minHeight, float *maxHeight)
Fills out the size limits set on the window.
_minWidth The minimum width of the window. _maxWidth The maximum width of the window. _minHeight The minimum height of the window. _maxHeight The maximum height of the window. BeOS R3
status_t BWindow::GetSupportedSuites(BMessage *data)
Reports the suites of messages and specifiers understood by the window.
BeOS R3
status_t BWindow::GetWindowAlignment(window_alignment *mode=NULL, int32 *h=NULL, int32 *hOffset=NULL, int32 *width=NULL, int32 *widthOffset=NULL, int32 *v=NULL, int32 *vOffset=NULL, int32 *height=NULL, int32 *heightOffset=NULL) const
Fills out the pointers with the alignment of the content of the window on the screen.
BeOS R3
void BWindow::Hide()
Removes the window from the screen, removes it from Deskbar's window list, and passes active status to another window.
Calls to Hide() and Show() are cumulative. BeOS R3
void BWindow::InvalidateLayout(bool descendants=false)
Invalidate layout.
descendants Also invalidate its children windows. Haiku R1
bool BWindow::InViewTransaction() const
Returns whether or not the window is currently in a view transaction.
true if the window is currently in a view transaction, false otherwise. Haiku R1
bool BWindow::IsActive() const
Returns whether or not the window is active.
true if the window is active, false otherwise. BeOS R3
bool BWindow::IsFloating() const
Returns whether or not the window is floating.
true if the window is floating, false otherwise. BeOS R3
bool BWindow::IsFront() const
Returns whether or not the window is the frontmost on screen.
true if window is the frontmost on screen, false otherwise. BeOS R3
bool BWindow::IsHidden() const
Returns whether or not the window is hidden.
Windows are hidden by default, you must call Show() to show the window starting the message loop going. BeOS R3
bool BWindow::IsMinimized() const
Returns whether or not the window is minimized.
true if the window is minimized, false otherwise. BeOS R5
bool BWindow::IsModal() const
Returns whether or not the window is modal.
true if the window is modal, false otherwise. BeOS R3
bool BWindow::IsOffscreenWindow() const
Tests if window is used for drawing into a BBitmap. This is mostly used by the Interface Kit itself.
True if the window is used for drawing into a BBitmap. Haiku R1
BMenuBar * BWindow::KeyMenuBar() const
Returns a pointer to the key menu bar set to the window.
If the window contains only one menu bar it is automatically considered to be the key menu bar for the window. If more than one menu bar is attached to the window then the last one added to the window's view hierarchy is considered to be the key menu bar for the window. To explicitly set a menu bar as the key menu bar call SetKeyMenuBar(). A pointer to the key menu bar or NULL is not is set. BeOS R3
BView * BWindow::LastMouseMovedView() const
Returns a pointer to the attached view that most recently received a B_MOUSE_MOVED message.
A pointer the BView object that most recently received a B_MOUSE_MOVED message or NULL if not found. BeOS R3
void BWindow::Layout(bool force)
Update the size limits and do the layout of the topmost view attached to the window.
force If true, layout even if valid. Haiku R1
window_look BWindow::Look() const
Returns the current window look flag.
The currently set window look flag. BeOS R3
void BWindow::MenusBeginning()
Hook method that gets called just before a menu owned by the window is shown.
This method is not invoked by a message, there is no B_MENUS_BEGINNING flag. BeOS R3
void BWindow::MenusEnded()
Hook method that gets called just before a menu owned by the window is hidden.
This method is not invoked by a message, there is no B_MENUS_ENDED flag. BeOS R3
void BWindow::MessageReceived(BMessage *message)
Handle message received by the associated looper.
message The message received by the looper. BHandler::MessageReceived() BeOS R3
void BWindow::Minimize(bool minimize)
Minimizes or un-minimizes the window based on minimize.
Unlike Hide() an Show(), Minimize() dims and un-dims the entry for the window in Deskbar's window list rather than removing it. Also Minimize() calls are not cumulative like Hide() and Show(); one false call will undo multiple true calls. Minimize() also acts as a hook method that is invoked when the user double- clicks on the title tab of the window or selects the window from the DeskBar window list. The minimize parameter is true if the window is about to be hidden and false if it is about to be shown. If you override Minimize() and you want to inherit BWindow's behavior, you must call BWindow::Minimize(). BeOS R3
void BWindow::MoveBy(float dx, float dy)
Move the window by dx pixels horizontally and dy pixels vertically.
dx and dy must be integral units. dx The number of pixels to move the window vertically. dy The number of pixels to move the window horizontally. BeOS R3
void BWindow::MoveOnScreen(uint32 flags=0)
Update window size and position to make it visible on screen.
This convenience method helps you to automatically move and resize a window to make it visible on the screen, in case the window is partially off screen because of its size or its position. This method will do nothing if the window fits on the screen. The default behavior is as follows: If the window size is larger than the screen, the window is resized so that it fits on the screen. If the window is still partially off-screen, it will then be centered horizontally and vertically so that it is fully visible. Note that this does not affect window size and positions for windows that are currently visible on the screen. Also note that this method does not affect whether the window is covered by other windows that are on top. You can use BWindow::Activate() to bring a window to the top. The behavior of this method can be altered by passing either or both of the following modifiers in the flags parameter: B_DO_NOT_RESIZE_TO_FIT Do not resize the window. If the window is too large to be on the screen, then it will at least be moved so that the left-top of the window is visible, and only the right and/or bottom of the window will be off screen. B_MOVE_IF_PARTIALLY_OFFSCREEN Use this parameter if instead of centering the window in the middle of the screen, you only want to do the minimum movement so that at least the top left part of the window is visible on screen. flags Can be 0 for the default behavior, or a any combination of B_DO_NOT_RESIZE_TO_FIT and B_MOVE_IF_PARTIALLY_OFFSCREEN. Haiku R1
void BWindow::MoveTo(BPoint)
Move the window to point.
point the location to move the window in the screen's coordinate system. BeOS R3
void BWindow::MoveTo(float x, float y)
Move the window to the specified x and y coordinates.
x and y must be integral units. x The horizontal coordinate to move the window to in the screen's coordinate system. y The vertical coordinate to move the window to in the screen's coordinate system. BeOS R3
bool BWindow::NeedsUpdate() const
Returns whether or not any of the attached views need to be updated.
true if an attached view needs to be updated, false otherwise. BeOS R3
virtual status_t BWindow::Perform(perform_code code, void *data)
Internal method.
Haiku R1
bigtime_t BWindow::PulseRate() const
Returns the pulse rate of the window.
B_PULSE messages are sent by default every 500,000 microseconds provided that no other messages are pending. The pulse rate of the window as a bigtime_t. BeOS R3
void BWindow::Quit()
Deletes the window and all child views, destroys the window thread, removes the window's connection to the Application Server, and deletes the object.
Use this method to destroy a window rather than using the delete operator. This method works much like the BLooper::Quit(), it doesn't return when called from the BWindow's thread and it returns after all messages have been processed when called from another thread and the BWindow and its thread has been destroyed. The window must first be locked before calling Quit(). BLooper::Quit() BeOS R3
Referenced by Close.
bool BWindow::QuitRequested()
Hook method that gets called when the window receives a B_QUIT_REQUESTED message.
Quit() BLooper::QuitRequested() BeOS R3
bool BWindow::RemoveChild(BView *child)
Removes child from the view hierarchy.
child The child view to remove. Whether or not child was removed from the view hierarchy. BeOS R3
status_t BWindow::RemoveFromSubset(BWindow *window)
Remove window from the subset of the BWindow.
A status code. B_OK window was removed from the subset of the BWindow. B_BAD_VALUE window is not B_NORMAL_WINDOW_FEEL or the BWindow object's feel is not set to B_MODAL_SUBSET_WINDOW_FEEL or B_FLOATING_SUBSET_WINDOW_FEEL. B_ERROR Could not lock the BWindow object. BeOS R3
void BWindow::ResizeBy(float dx, float dy)
Resize the window by dx pixels horizontally and dy pixels vertically.
dx and dy must be integral units. dx The number of pixels to resize the window horizontally. dy The number of pixels to resize the window vertically. BeOS R3
void BWindow::ResizeTo(float width, float height)
Resize the window to the specified width and height.
width and height must be integral units. width The width to resize the window to. height The height to resize the window to. BeOS R3
void BWindow::ResizeToPreferred()
Resize the window to the preferred size of the window's layout.
Haiku R1
BHandler * BWindow::ResolveSpecifier(BMessage *message, int32 index, BMessage *specifier, int32 what, const char *property)
Determine the proper handler for a scripting message. message The scripting message to determine the handler. index The index of the specifier. specifier The message which contains the specifier. what The 'what' field of the specifier message. property The name of the target property. A pointer to the proper BHandler for the given scripting message. BeOS R3
thread_id BWindow::Run()
Spawns the message loop thread and starts the window running.
BLooper::Run() BeOS R3
void BWindow::ScreenChanged(BRect screenSize, color_space depth)
Hook method that is called when the screen that the window is located on changes size or location or the color space of the screen changes.
screenSize The new screen size in the screen's coordinate system. depth The new color space of the screen. BeOS R3
status_t BWindow::SendBehind(const BWindow *window)
Moves the BWindow object behind window.
window A pointer to the window to move behind. B_OK on success or B_ERROR on failure. BeOS R3
status_t BWindow::SetDecoratorSettings(const BMessage &settings)
Set the window decorator settings according to settings.
settings The decorator settings message to set. B_OK if the decorator settings were set successfully or an error code otherwise. Haiku R1
void BWindow::SetDefaultButton(BButton *button)
Set the default button of the window to button.
The default button has a grey outline and is activated by the user pushing the Enter key. The user can activate the default button even if another view is currently set to be the focus view of the window. A window may only have one default button at a time, to remove the current default without setting another button you may pass in NULL. button A pointer to the button to set as the default or NULL to unset. BeOS R3
status_t BWindow::SetFeel(window_feel feel)
Changes the window feel set in the constructor to feel.
B_OK on success or an error code on failure. BeOS R3
status_t BWindow::SetFlags(uint32)
Changes the window flags set in the constructor to flags.
B_OK on success or an error code on failure. BeOS R3
void BWindow::SetKeyMenuBar(BMenuBar *bar)
Set the specified menu bar as the key menu bar for the window.
The key menu bar is the one located at the top of the window at the root of the menu hierarchy that the user can navigate with the keyboard. bar A pointer to the menu bar to set as as the key menu bar for the window. BeOS R3
void BWindow::SetLayout(BLayout *layout)
Sets the layout of the window.
layout The layout to set. Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::Cards, BLayoutBuilder::Grid< ParentBuilder >::Grid, BLayoutBuilder::Group< ParentBuilder >::Group.
status_t BWindow::SetLook(window_look look)
Changes the window look set in the constructor to look.
B_OK on success or an error code on failure. BeOS R3
void BWindow::SetPulseRate(bigtime_t rate)
Sets how often B_PULSE messages are posted to the window.
All BViews attached to a window share the same pulse rate. rate should not be set to less than 100,000 microseconds, differences less than 50,000 microseconds may not be noticeable. Setting the rate to 0 disables pulsing for all views attache to the window. rate The pulse rate to set. BeOS R3
void BWindow::SetSizeLimits(float minWidth, float maxWidth, float minHeight, float maxHeight)
Set size limits on the window.
The user won't be able to resize the window beyond the limits set by this method. SetSizeLimits() constrains the user, not the programmer, you may still resize the window outside of the size limits set by this method by calling ResizeBy() or ResizeTo(). minWidth The minimum width of the window to set. maxWidth The maximum width of the window to set. minHeight The minimum height of the window to set. maxHeight The maximum height of the window to set. BeOS R3
void BWindow::SetTitle(const char *title)
Sets the window title to title.
Also renames the window thread to "w>title" where "title" is the passed in title string. BeOS R5
status_t BWindow::SetType(window_type type)
Changes the window type set in the constructor to type.
B_OK on success or an error code on failure. BeOS R3
status_t BWindow::SetWindowAlignment(window_alignment mode, int32 h, int32 hOffset=0, int32 width=0, int32 widthOffset=0, int32 v=0, int32 vOffset=0, int32 height=0, int32 heightOffset=0)
Sets the alignment of the content of the window on the screen.
BeOS R3
void BWindow::SetWorkspaces(uint32)
Sets the set of workspaces where the window can be displayed.
workspaces B_CURRENT_WORKSPACE to place the window in the currently displayed workspace removing it from all others. B_ALL_WORKSPACES to make the window show up in all workspaces. BeOS R3
void BWindow::SetZoomLimits(float maxWidth, float maxHeight)
Sets the maximum size that the window will zoom to when Zoom() is called.
The window will zoom to the minimum of the screen size, the maximum values set by SetSizeLimits(), and the maximum values set by this method. /see Zoom() BeOS R3
void BWindow::Show()
Shows the window on screen, places it frontmost on the screen, adds the window to Deskbar's window list, and makes it the active window.
If this is the first time Show() has been called on the window the message loop is started and it is unlocked. Calls to Hide() and Show() are cumulative. BeOS R3
BSize BWindow::Size() const
Returns the size of the window.
The size of the window as a BSize in the screen coordinate system. Haiku R1
void BWindow::Sync() const
Synchronizes the attached window's connection to App Server causing any pending messages to be processed and then waits for the App Server to respond.
BeOS R3
const char * BWindow::Title() const
Returns the window title as set by the constructor or SetTitle().
A pointer to the window title. BeOS R3
window_type BWindow::Type() const
Returns the current window type flag.
The currently set window type flag. BeOS R3
void BWindow::UpdateIfNeeded()
Invokes Draw() immediately on each child view that needs updating.
This method is synchronous, it waits for each child view to update before returning. This method is ignored unless it is called from within the message loop of the thread that the BWindow is running in. You may call this method as part of a hook function such as MouseMoved() or KeyDown() to force invalid views to be immediately redrawn without having to wait for the hook function to finish. BeOS R3
void BWindow::UpdateSizeLimits()
Updates the window's size limits from the minimum and maximum sizes of its top view.
This method does nothing unless the B_AUTO_UPDATE_SIZE_LIMITS window flag is set. The method is called automatically after a layout invalidation. Since it is invoked asynchronously, calling this method manually is necessary, if it is desired to adjust the limits (and as a possible side effect the window size) earlier, e.g. before the first call to the Show() method.) Haiku R1
void BWindow::WindowActivated(bool focus)
Hook method that gets called when the window becomes activated or deactivated.
active true if the window has become activated, false if the window has become deactivated. BeOS R3
void BWindow::WorkspaceActivated(int32 workspace, bool state)
Hook method that gets called when the active workspace changes.
This method is only called when a workspace in which the window resides is activated or deactivated. workspace The workspace number that was activated/deactivated. state true if activated, false if deactivated. BeOS R3
uint32 BWindow::Workspaces() const
Returns the set of workspaces where the window can be displayed.
BeOS R3
void BWindow::WorkspacesChanged(uint32 oldWorkspaces, uint32 newWorkspaces)
Hook method that gets called whenever the workspaces the window is in changes.
oldWorkspaces The old set of workspaces the window was visible in. newWorkspaces The new set of workspaces the window is visible in. BeOS R3
void BWindow::Zoom()
Resize the window to the minimum of the screen size, the maximum values set by SetSizeLimits(), and the maximum values set by SetZoomLimits().
You may call Zoom() even if the window has the B_NOT_ZOOMABLE flag set. This is the method called when the user clicks the window's zoom button. It can also be called programmatically. The window dimensions are calculated from the smallest of three rectangles: the screen frame, the rectangle defined by SetZoomLimits(), the rectangle defined by SetSizeLimits(). However if the window frame already matches these new dimensions, Zoom() uses the previous size and location of the window instead. This method calls Zoom(BPoint, float, float) to do the actualy zooming. Zoom(BPoint, float, float); BeOS R3
void BWindow::Zoom(BPoint origin, float width, float height)
Move window to origin, then resize to width and height.
You may call Zoom() even if the window has the B_NOT_ZOOMABLE flag set. This method may move and resize the window resulting in both the FrameMoved() and FrameResized() hook methods to be called. You can override this method to change how your window behaves when the user clicks the zoom button or when Zoom() is called. origin The point that the window was moved to. width The new width of the window. height The new height of the window. BeOS R3
BArchivable * BWindow::Instantiate(BMessage *archive)
Creates a new BWindow object from the data message.
data A pointer to the BMessage object to build the object from. A newly created BWindow object or NULL if the message doesn't contain an archived BWindow. BeOS R3
BWindow::BWindow()
BWindow::BWindow(BRect frame, int32 bitmapToken)
Offscreen bitmap constructor.
frame The inner frame rectangle in the screen coordinate system. bitmapToken Token to pass into App Server for offscreen window bitmap. Haiku R1
BWindow::BWindow(BWindow &)
void BWindow::_AdoptResize()
window_type BWindow::_ComposeType(window_look look, window_feel feel) const
void BWindow::_CreateTopView()
void BWindow::_DecomposeType(window_type type, window_look *look, window_feel *feel) const
void BWindow::_DequeueAll()
BHandler * BWindow::_DetermineTarget(BMessage *message, BHandler *target)
BView * BWindow::_FindNextNavigable(BView *focus, uint32 flags)
BView * BWindow::_FindPreviousNavigable(BView *focus, uint32 flags)
Shortcut * BWindow::_FindShortcut(uint32 key, uint32 modifiers)
BView * BWindow::_FindView(BView *view, BPoint point) const
BView * BWindow::_FindView(int32 token)
void BWindow::_GetDecoratorSize(float *_borderWidth, float *_tabHeight) const
bool BWindow::_HandleKeyDown(BMessage *event)
bool BWindow::_HandleUnmappedKeyDown(BMessage *event)
void BWindow::_InitData(BRect frame, const char *title, window_look look, window_feel feel, uint32 flags, uint32 workspace, int32 bitmapToken=-1)
bool BWindow::_IsFocusMessage(BMessage *message)
void BWindow::_KeyboardNavigation()
BView * BWindow::_LastViewChild(BView *parent)
void BWindow::_PropagateMessageToChildViews(BMessage *)
virtual void BWindow::_ReservedWindow2()
virtual void BWindow::_ReservedWindow3()
virtual void BWindow::_ReservedWindow4()
virtual void BWindow::_ReservedWindow5()
virtual void BWindow::_ReservedWindow6()
virtual void BWindow::_ReservedWindow7()
virtual void BWindow::_ReservedWindow8()
void BWindow::_SanitizeMessage(BMessage *message, BHandler *target, bool usePreferred)
void BWindow::_SendShowOrHideMessage()
void BWindow::_SetFocus(BView *focusView, bool notifyIputServer=false)
void BWindow::_SetName(const char *title)
bool BWindow::_StealMouseMessage(BMessage *message, bool &deleteMessage)
void BWindow::_Switcher(int32 rawKey, uint32 modifiers, bool repeat)
uint32 BWindow::_TransitForMouseMoved(BView *view, BView *viewUnderMouse) const
bool BWindow::_UnpackMessage(unpack_cookie &state, BMessage **_message, BHandler **_target, bool *_usePreferred)
BPoint BWindow::AlertPosition(const BRect &frame)
virtual BMessage * BWindow::ConvertToMessage(void *raw, int32 code)
bool BWindow::InUpdate()
bool BWindow::IsFilePanel() const
BWindow & BWindow::operator=(BWindow &)
void BWindow::SetIsFilePanel(bool yes)
virtual void BWindow::task_looper()