BLayoutBuilder::Cards
BLayoutBuilder::Cards< ParentBuilder >::Cards()
Creates a builder for BCardLayout.
Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::Cards(BWindow *window)
Creates a new builder for BCardLayout, and attaches it to a window.
Haiku R1
References BLayout::Owner, BWindow::SetLayout, BView::SetViewColor.
BLayoutBuilder::Cards< ParentBuilder >::Cards(BView *view)
Creates a new builder for BCardLayout, and attaches it to a view.
Haiku R1
References BView::SetLayout, BView::SetViewColor.
BLayoutBuilder::Cards< ParentBuilder >::Cards(BCardLayout *layout)
Creates a builder targeting an existing BCardLayout.
Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::Cards(BCardView *view)
Creates a builder targeting an existing BCardView.
Haiku R1
BCardLayout * BLayoutBuilder::Cards< ParentBuilder >::Layout() const
Get a pointer to the layout this builder represents. Haiku R1
BView * BLayoutBuilder::Cards< ParentBuilder >::View() const
Get a pointer to the BView this builder's layout is attached to. Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::AddCards, BLayoutBuilder::Group< ParentBuilder >::AddCards, BLayoutBuilder::Split< ParentBuilder >::AddCards, BLayoutBuilder::Grid< ParentBuilder >::AddCards.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::GetLayout(BCardLayout **_layout)
Get the layout this builder represents. _layout The layout this builder represents. Haiku R1
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::GetView(BView **_view)
Get a pointer to the BView this builder's layout is attached to. _view The BView this builder's layout is attached to. Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::operator BCardLayout *()
Cast this builder into the layout object it represents.
Haiku R1
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::Add(BView *view)
Add a view to the underlying BCardLayout.
The layout item will be added as a card at the end of the stack. view The BView to be added. The underlying BCardLayout will take ownership of the object. Haiku R1
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::Add(BLayoutItem *item)
Add a item to the underlying BCardLayout.
The layout item will be added as a card at the end of the stack. item The BLayoutItem to be added. The underlying BCardLayout will take ownership of the object. Haiku R1
Cards< ParentBuilder >::GroupBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGroup(orientation orientation, float spacing=B_USE_DEFAULT_SPACING)
BLayoutBuilder::Group<ParentBuilder>::AddGroup( orientation orientation, float spacing, float weight) orientation The orientation to use for the new BGroupLayout. spacing The spacing to use for the new BGroupLayout. A GroupBuilder representing the newly created BGroupLayout. Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::GroupBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGroup(BGroupView *groupView)
BLayoutBuilder::Group<ParentBuilder>::AddGroup( BGroupLayout* groupLayout, float weight) groupView The BGroupView to be added. A GroupBuilder representing the layout of the groupView. Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::GroupBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGroup(BGroupLayout *groupLayout)
BLayoutBuilder::Group<ParentBuilder>::AddGroup(BGroupView* groupView, float weight) groupLayout The BGroupLayout to be added. A GroupBuilder representing the groupLayout. Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::GridBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGrid(float horizontal=B_USE_DEFAULT_SPACING, float vertical=B_USE_DEFAULT_SPACING)
BLayoutBuilder::Group<ParentBuilder>::AddGrid( float horizontalSpacing, float verticalSpacing, float weight) Shorthand for builders returned by this builder's AddGrid() methods. Haiku R1 BLayoutBuilder::Group<ParentBuilder>::AddGrid( float horizontalSpacing, float verticalSpacing, float weight) horizontalSpacing The horizontal spacing for the new BGridLayout. verticalSpacing The vertical spacing for the new BGridLayout. A GridBuilder representing the newly created BGridLayout. Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::GridBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGrid(BGridLayout *gridLayout)
BLayoutBuilder::Group<ParentBuilder>::AddGrid( BGridLayout* gridLayout, float weight) gridLayout The BGridLayout to be added and used to construct the returned GridBuilder. A GridBuilder representing gridLayout. Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::GridBuilder BLayoutBuilder::Cards< ParentBuilder >::AddGrid(BGridView *gridView)
BLayoutBuilder::Group<ParentBuilder>::AddGrid( BGridView* gridView, float weight) gridView The BGridView to be added and used to construct the returned GridBuilder. A GridBuilder representing the layout of the gridView. Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout, BLayoutBuilder::Base< ParentBuilder >::SetParent.
Cards< ParentBuilder >::SplitBuilder BLayoutBuilder::Cards< ParentBuilder >::AddSplit(orientation orientation, float spacing=B_USE_DEFAULT_SPACING)
BLayoutBuilder::Group<ParentBuilder>::AddSplit( orientation orientation, float spacing, float weight) orientation The orientation of the new BSplitView. spacing The spacing of the new BSplitView. A SplitBuilder representing the new BSplitView. Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent, BLayoutBuilder::Split< ParentBuilder >::View.
Cards< ParentBuilder >::SplitBuilder BLayoutBuilder::Cards< ParentBuilder >::AddSplit(BSplitView *splitView)
BLayoutBuilder::Group<ParentBuilder>::AddSplit( BSplitView* splitView, float weight) splitView The BSplitView to be added. A SplitBuilder representing the splitView. Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent, BLayoutBuilder::Split< ParentBuilder >::View.
Cards< ParentBuilder >::CardBuilder BLayoutBuilder::Cards< ParentBuilder >::AddCards()
BLayoutBuilder::Group<ParentBuilder>::AddCards( float weight) A CardBuilder representing the new BCardLayout. Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent, BLayoutBuilder::Cards< ParentBuilder >::View.
Cards< ParentBuilder >::CardBuilder BLayoutBuilder::Cards< ParentBuilder >::AddCards(BCardLayout *cardLayout)
BLayoutBuilder::Group<ParentBuilder>::AddCards( BCardLayout* cardLayout, float weight) cardLayout The existing layout that will be added to the underlying BSplitView. A CardBuilder representing the cardLayout. Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent, BLayoutBuilder::Cards< ParentBuilder >::View.
Cards< ParentBuilder >::CardBuilder BLayoutBuilder::Cards< ParentBuilder >::AddCards(BCardView *cardView)
BLayoutBuilder::Group<ParentBuilder>::AddCards( BCardView* cardView, float weight) cardView The existing view that will be added to the underlying BSplitView. A CardBuilder representing the layout of t he cardView. Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent, BLayoutBuilder::Cards< ParentBuilder >::View.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMinSize(BSize size)
Set the explicit minimum size of the underlying layout. Haiku R1
References BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMinSize.
Referenced by BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMinSize.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMaxSize(BSize size)
Set the explicit maximum size of the underlying layout. Haiku R1
References BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMaxSize.
Referenced by BLayoutBuilder::Cards< ParentBuilder >::SetExplicitMaxSize.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::SetExplicitPreferredSize(BSize size)
Set the explicit preferred size of the underlying layout. Haiku R1
References BLayoutBuilder::Cards< ParentBuilder >::SetExplicitPreferredSize.
Referenced by BLayoutBuilder::Cards< ParentBuilder >::SetExplicitPreferredSize.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::SetExplicitAlignment(BAlignment alignment)
Set the explicit alignment of the underlying layout. Haiku R1
References BLayoutBuilder::Cards< ParentBuilder >::SetExplicitAlignment.
Referenced by BLayoutBuilder::Cards< ParentBuilder >::SetExplicitAlignment.
Cards< ParentBuilder >::ThisBuilder & BLayoutBuilder::Cards< ParentBuilder >::SetVisibleItem(int32 index)
Set the current visible item to the item at index.
BCardLayout::SetVisibleItem(int32)
References BLayoutBuilder::Cards< ParentBuilder >::SetVisibleItem.
Referenced by BLayoutBuilder::Cards< ParentBuilder >::SetVisibleItem.
BLayoutBuilder::Cards< ParentBuilder >::CardBuilder
Shorthand for builders returned by this builder's AddCards() methods. Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::GridBuilder
Shorthand for builders returned by this builder's AddGrid() methods. Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::GroupBuilder
Shorthand for builders returned by this builder's AddGroup() methods. Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::SplitBuilder
Shorthand for builders returned by this builder's AddSplit() methods. Haiku R1
BLayoutBuilder::Cards< ParentBuilder >::ThisBuilder
Shorthand representing the type of this. Haiku R1
BCardLayout* BLayoutBuilder::Cards< ParentBuilder >::fLayout