BList
BList & BList::operator=(const BList &other)
Copy another list into this object.
BeOS R3
bool BList::operator==(const BList &other) const
Returns whether or not the BList and other are equal.
Equal means that they are the same object or their contents are the same. true if the lists are equal, false if they are NOT equal. Haiku R1
bool BList::operator!=(const BList &other) const
Returns whether or not the BList and other are NOT equal.
true if the lists are NOT equal, false if they are equal. Haiku R1
bool BList::AddItem(void *item, int32 index)
Add item at the specified index.
item The item to add. index The place in the list to add the item. Whether or not the item was added. true The item was added. false Item was not added. Either the index is negative or invalid, or resizing the list failed. AddItem(void*) BeOS R3
Referenced by BObjectList< T >::AddItem.
bool BList::AddItem(void *item)
Append the item to the end of the list.
item The item to append. Whether or not the item was appended. true The item was appended. false item was not appended, since resizing the BList failed. AddItem(void*, int32) BeOS R3
bool BList::AddList(const BList *list, int32 index)
Add a list of items to this list at the specified index.
Note that the list parameter is const, so the original list will not be altered. list The list to be added. index The position in the current list where the new item(s) are added. Whether or not the list was added. true The list was added. false Failed to insert the list resizing failed. AddList(const BList*) BeOS R3
Referenced by BObjectList< T >::AddList.
bool BList::AddList(const BList *list)
Append a list of items to this list.
Note that the list parameter is a const, so the original list will not be altered. list The list to be added. Whether or not the list was added. true The list was appended. false Failed to append the list, resizing failed. AddList(const BList*, int32) BeOS R3
bool BList::RemoveItem(void *item)
Remove item from the list.
item The item to be removed. Whether or not the item was removed. true The item was found and removed. false The item was not in this list and thus not removed. RemoveItem(int32) BeOS R3
Referenced by BObjectList< T >::RemoveItem, BObjectList< T >::RemoveItemAt.
void * BList::RemoveItem(int32 index)
Remove the item at index from the list.
index The index of the item to be removed. The pointer to the item that was removed, or NULL if the index was invalid. RemoveItem(void*) BeOS R3
bool BList::RemoveItems(int32 index, int32 count)
Remove a number of items starting at a certain position.
If the count parameter is larger than the number of items in the list, all the items from the offset to the end will be removed. index The offset in the list where removal should start. count The number of items to remove. Whether or not the items were removed. true Removal succeeded. false Failed to remove the items because the index was invalid. BeOS R3
bool BList::ReplaceItem(int32 index, void *item)
Replace an item with another one.
index The offset in the list where to put the item. item The new item to put in the list. Whether or not the item was replaced. true The item was replaced. false The index was invalid. Haiku R1
void BList::MakeEmpty()
Clear all the items from the list.
This does not free the items. BeOS R3
Referenced by BObjectList< T >::MakeEmpty.
void BList::SortItems(int(*compareFunc)(const void *, const void *))
Sort the items with the use of a supplied comparison function.
The function should take two const pointers as arguments and should return an integer. For an example, see the Compare(const BString *, const BString *) function. BeOS R3
Referenced by BObjectList< T >::SortItems.
bool BList::SwapItems(int32 indexA, int32 indexB)
Swap the items at indexA and indexB.
indexA The first item. indexB The second item. Whether or not the items were swapped. true Swap succeeded. false Swap failed because one of the indexes was invalid. Haiku R1
bool BList::MoveItem(int32 from, int32 to)
Move the item at fromIndex to the position of toIndex.
This moves a list item from position A to position B, moving the appropriate block of list elements to make up for the move. For example, in the array: A B C D E F G H I J Moving 1(B)->6(G) would result in this: A C D E F G B H I J fromIndex The original location. toIndex The new location. Whether or not the items were moved. true Move succeeded. false Move failed due to the indexes being invalid. Haiku R1
void * BList::ItemAt(int32 index) const
Return a pointer to the item at the given index.
index The item to retrieve. A pointer to the item in that position, or NULL if the index is out of bounds. ItemAtFast(int32 index) const BeOS R3
Referenced by BObjectList< T >::ItemAt.
void * BList::FirstItem() const
Return a pointer to the first item in the list.
A pointer to the first item or NULL if the list is empty. LastItem() const BeOS R3
Referenced by BObjectList< T >::FirstItem.
void * BList::ItemAtFast(int32 index) const
Return a pointer to the item at index.
This method does not perform any boundary checks when it retrieves an item. Use this method in a performance critical area of your program where you are sure you will not get an invalid item. A pointer to the item. Haiku R1
void * BList::LastItem() const
Return a pointer to the last item in the list.
A pointer to the last item or NULL if the list is empty. FirstItem() const BeOS R3
Referenced by BObjectList< T >::LastItem.
void * BList::Items() const
Return the internal list of objects.
This method will return a pointer to the internal pointer list. This means that you should be careful what you are doing, since you are working with the internals of the class directly. It is not a good idea to make any changes to the list, since that will mess up the internal consistency. If there is anything you want, for which you need the list of objects, please realize that that probably means that what you want to do is a bad idea to begin with and that you should avoid this method. The list of objects does not belong to you. The internal list of pointers. DoForEach() for an alternate method. BeOS R3
bool BList::HasItem(void *item) const
Return whether or not item is in the list.
true if the item was in the list, false otherwise. BeOS R3
Referenced by BObjectList< T >::HasItem.
bool BList::HasItem(const void *item) const
Return whether or not item is in the list.
true if the item was in the list, false otherwise. Haiku R1
int32 BList::IndexOf(void *item) const
Return the index of item.
The index of the item, or -1 when the item is not in the list. BeOS R3
Referenced by BObjectList< T >::IndexOf.
int32 BList::IndexOf(const void *item) const
Return the index of item.
The index of the item, or -1 when the item is not in the list. Haiku R1
int32 BList::CountItems() const
Returns the number of items in the list.
The number of items in the list as an int32. BeOS R3
Referenced by BObjectList< T >::CountItems.
bool BList::IsEmpty() const
Return whether or not there are items in the list.
true if the list was empty, false otherwise. BeOS R3
Referenced by BObjectList< T >::IsEmpty.
void BList::DoForEach(bool(*func)(void *item))
Perform an action on every item in the list.
Iterates over all items in the list, and calls the func function on each of them, until the function returns true. func A pointer to a function that takes a void* list item, and returns a bool indicating if the iteration should stop. DoForEach(bool (*func)(void*, void*), void*) BeOS R3
void BList::DoForEach(bool(*func)(void *item, void *arg2), void *arg2)
Perform an action on every item in the list with an argument.
The iteration stops when the func function returns true. This can be used to implement a linear search of the list, for example: boolcompareFunc(void*_item,void*arg2){ Item*item=(Item*)_item; Args*args=(Args*)arg2; if(item->Matches(args->pattern)){ args->result=item; returntrue; } returnfalse; } Argsargs={0}; list.DoForEach(compareFunc,&args); if(args->result!=NULL){ //Foundit! } func A function with the first void* argument being the item and the second void* being the argument that you supply. arg2 An argument to supply to func. DoForEach(bool (*func)(void*)) BeOS R3
uint32 BList::_reserved[1][1]
int32 BList::fBlockSize
int32 BList::fItemCount
void** BList::fObjectList
int32 BList::fPhysicalSize
int32 BList::fResizeThreshold
BList::BList(const BList &other)
Copy constructor. Copy a complete list into this one.
other The list to copy from. BeOS R3
BList::BList(int32 count=20)
Create a new list with a number of empty slots.
The memory management of this class allocates new memory per block. The count parameter can be tweaked to determine the size of these blocks. In general, if you know your list is only going to contain a certain number of items at most, you can pass that value. If you expect your list to have very few items, it is safe to choose a low number. This is to prevent the list from taking up unneeded memory. If you expect the list to contain a large number of items, choose a higher value. Every time the memory is full, all the items have to be copied into a new piece of allocated memory, which is an expensive operation. If you are unsure, you do not have to worry too much. Just make sure you do not use a lot of lists, and as long as the list is not used in one of the performance critical parts of the code, you are safe to go with the default values. count The size of the blocks allocated in memory. BeOS R3
BList::~BList()
Destroy the list.
Please note that as BList does not assume ownership of the objects, only the list will be freed, not the objects that are held in it. BeOS R3
virtual void BList::_ReservedList1()
virtual void BList::_ReservedList2()
bool BList::_ResizeArray(int32 count)