BObjectList
BObjectList< T > & BObjectList< T >::operator=(const BObjectList &list)
Creates a new BObjectList as a copy of another list by overloading the = operator.
list The list to copy from. Haiku R1
References BObjectList< T >::CountItems, BObjectList< T >::ItemAt.
bool BObjectList< T >::AddItem(T *)
Append the item to the end of the list.
item The item to append. Whether or not the item was appended. true The item was appended. false item was not appended, since resizing the BObjectList failed. Haiku R1
References BList::AddItem.
bool BObjectList< T >::AddItem(T *, int32)
Add item at the specified index.
item The item to add. index The place in the list to add the item. Whether or not the item was added. true The item was added. false Item was not added. Either the index is negative or invalid, or resizing the BObjectList failed. Haiku R1
References BList::AddItem.
bool BObjectList< T >::AddList(BObjectList *)
Append a list of items to this list.
The original list is not altered. list The list to be added. Whether or not the list was added. true The list was added. false Failed to append the list, resizing failed. Haiku R1
References BList::AddList.
bool BObjectList< T >::AddList(BObjectList *, int32)
Add a list of items to this list at the specified index.
The original list is not altered. list The list to be added. index The position in the current list where the new item(s) are added. Whether or not the list was added. true The list was added. false Failed to insert the list resizing failed. Haiku R1
References BList::AddList.
bool BObjectList< T >::RemoveItem(T *, bool deleteIfOwning=true)
Remove item from the list.
item The item to be removed. deleteIfOwning Also delete the item if owned. Whether or not the item was removed. true The item was found and removed. false The item was not in this list and thus not removed. Haiku R1
References BList::RemoveItem.
T * BObjectList< T >::RemoveItemAt(int32)
Remove the item at index from the list.
index The index of the item to be removed. The pointer to the item that was removed, or NULL if the index was invalid. Haiku R1
References BList::RemoveItem.
void BObjectList< T >::MakeEmpty(bool deleteIfOwning=true)
Clear all the items from the list.
deleteIfOwning Also deletes items if owned. Haiku R1
References BList::MakeEmpty.
T * BObjectList< T >::ItemAt(int32) const
Return a pointer to the item at the given index.
index The item to retrieve. A pointer to the item in that position, or NULL if the index is out of bounds. Haiku R1
References BList::ItemAt.
Referenced by BObjectList< T >::BObjectList, BObjectList< T >::operator=.
bool BObjectList< T >::ReplaceItem(int32 index, T *)
Replace an item with another one.
index The offset in the list where to put the item. item The new item to put in the list. Whether or not the item was replaced. true The item was replaced. false The index was invalid. Haiku R1
T * BObjectList< T >::SwapWithItem(int32 index, T *newItem)
Swap the item with the item at index.
index The offset in the list where to put the item. item The new item to put in the list. A pointer to the item in that position, or NULL if the index is out of bounds. Haiku R1
bool BObjectList< T >::MoveItem(int32 from, int32 to)
Move the item at from to the position of to.
from The index to move the item from. to The index to move the item to. Whether or not the items were moved. true The items were moved. false The from or to index was invalid. BList::MoveItem() Haiku R1
void BObjectList< T >::SortItems(CompareFunction)
Sort the items with the use of a supplied comparison function.
function The function used to sort the items. Haiku R1
References BList::SortItems.
void BObjectList< T >::SortItems(CompareFunctionWithState, void *state)
Sort the items with the use of a supplied comparison function and addtional state.
function The function used to sort the items. state Additional information used to sort the items. Haiku R1
References BList::SortItems.
void BObjectList< T >::HSortItems(CompareFunction)
Sort the items with the use of a supplied comparison function.
function The function used to sort the items. Haiku R1
T * BObjectList< T >::FirstItem() const
Return a pointer to the first item in the list.
A pointer to the first item or NULL if the list is empty. BObjectList<T>::LastItem() const Haiku R1
References BList::FirstItem.
T * BObjectList< T >::LastItem() const
Return a pointer to the last item in the list.
A pointer to the last item or NULL if the list is empty. BObjectList<T>::FirstItem() const Haiku R1
References BList::LastItem.
int32 BObjectList< T >::IndexOf(const T *) const
Return the index of item.
The index of the item, or -1 when the item is not in the list. Haiku R1
References BList::IndexOf.
bool BObjectList< T >::HasItem(const T *) const
Return whether or not item is in the list.
true if the item was in the list, false otherwise. Haiku R1
References BList::HasItem.
bool BObjectList< T >::IsEmpty() const
Return whether or not there are items in the list.
true if the list was empty, false otherwise. Haiku R1
References BList::IsEmpty.
int32 BObjectList< T >::CountItems() const
Returns the number of items in the list.
The number of items in the list as an int32. Haiku R1
References BList::CountItems.
Referenced by BObjectList< T >::BObjectList, BObjectList< T >::operator=.
T * BObjectList< T >::EachElement(EachFunction, void *)
Perform an action on each item in the list.
func A function that takes a void* argument and returns a boolean. params parameters for func. A pointer to the item. Haiku R1
const T * BObjectList< T >::EachElement(ConstEachFunction, void *) const
Perform an action on each item in the list.
func A function that takes a void* argument and returns a boolean. params parameters for func. A pointer to the item. Haiku R1
const T * BObjectList< T >::FindIf(const UnaryPredicate< T > &) const
Find items that match predicate.
A const pointer to T. Haiku R1
T * BObjectList< T >::FindIf(const UnaryPredicate< T > &)
Find items that match predicate.
A pointer to T. Haiku R1
T * BObjectList< T >::BinarySearch(const T &, CompareFunction) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
key The key to search for. func The comparison function to use. A pointer to T. Haiku R1
T * BObjectList< T >::BinarySearch(const T &, CompareFunctionWithState, void *state) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
key The key to search for. func The comparison function to use. state Additional information used to search for the item. A pointer to T. Haiku R1
typedef int(* BObjectList< T >::CompareFunction) (const T *, const T *))(const T *, const T *)
typedef int(* BObjectList< T >::CompareFunctionWithState) (const T *, const T *, void *state))(const T *, const T *, void *state)
typedef const T *(* BObjectList< T >::ConstEachFunction) (const T *, void *))(const T *, void *)
typedef T *(* BObjectList< T >::EachFunction) (T *, void *))(T *, void *)
friend class Private
BObjectList< T >::BObjectList(const BObjectList &list)
Creates a new BObjectList as a copy of another list.
list The list to copy from. Haiku R1
References BObjectList< T >::CountItems, BObjectList< T >::ItemAt.
BObjectList< T >::BObjectList(int32 itemsPerBlock=20, bool owning=false)
Creates a new BObjectList.
itemsPerBlock The number of items per block to allocate. owning Whether or not the BObjectList deletes its items when it is emptied or deleted. Haiku R1
BObjectList< T >::~BObjectList()
Deletes the list.
If the list owns its items they are deleted too. Haiku R1
bool BObjectList< T >::BinaryInsert(T *, CompareFunction)
bool BObjectList< T >::BinaryInsert(T *, CompareFunctionWithState, void *state)
bool BObjectList< T >::BinaryInsert(T *, const UnaryPredicate< T > &)
T * BObjectList< T >::BinaryInsertCopy(const T &copyThis, CompareFunction)
T * BObjectList< T >::BinaryInsertCopy(const T &copyThis, CompareFunctionWithState, void *state)
T * BObjectList< T >::BinaryInsertCopyUnique(const T &copyThis, CompareFunction)
T * BObjectList< T >::BinaryInsertCopyUnique(const T &copyThis, CompareFunctionWithState, void *state)
bool BObjectList< T >::BinaryInsertUnique(T *, CompareFunction)
bool BObjectList< T >::BinaryInsertUnique(T *, CompareFunctionWithState, void *state)
bool BObjectList< T >::BinaryInsertUnique(T *, const UnaryPredicate< T > &)
T * BObjectList< T >::BinarySearchByKey(const Key &key, int(*compare)(const Key *, const T *)) const
T * BObjectList< T >::BinarySearchByKey(const Key &key, int(*compare)(const Key *, const T *, void *), void *state) const
int32 BObjectList< T >::BinarySearchIndex(const T &item, CompareFunction compare) const
int32 BObjectList< T >::BinarySearchIndex(const T &item, CompareFunctionWithState compare, void *state) const
int32 BObjectList< T >::BinarySearchIndexByKey(const Key &key, int(*compare)(const Key *, const T *)) const
int32 BObjectList< T >::FindBinaryInsertionIndex(const UnaryPredicate< T > &, bool *alreadyInList=0) const
void BObjectList< T >::HSortItems(CompareFunctionWithState, void *state)
void BObjectList< T >::_SetItem(int32, T *)